services:
  front:
    build: ./web
    image: transport-front
    ports:
      - 8080:8080
    container_name: transport-front
    depends_on:
      - api
  api:
    build: ./api
    image: transport-api
    ports:
      - 8081:8081
    container_name: transport-api
    depends_on:
      - db
  db:
    build: ./db
    image: transport-db
    ports:
      - 3306:3306
    container_name: transport-db
