[project]
name = "lw2bd"
version = "0.1.0"
description = "backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.0",
    "pymysql[rsa]>=1.1.2",
    "sqlalchemy>=2.0.44",
    "uvicorn>=0.37.0",
]
