[project]
name = "lw2bd"
version = "0.1.0"
description = "backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.0",
    "sqlmodel>=0.0.27",
    "uvicorn>=0.37.0",
]
